<?php

namespace Database\Seeders;

use App\Models\Ingredients;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IngredientsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $saveList=[
            ['name'=>'Ayam dada fillet', 'unit'=>'1000', 'default_price'=>'47000', 'satuan'=>'gram'],
            ['name'=>'Sosis Sapi ( Charm isi 15 )', 'unit'=>'375', 'default_price'=>'30000', 'satuan'=>'gram'],
            ['name'=>'Lidah', 'unit'=>'1000', 'default_price'=>'95000', 'satuan'=>'gram'],
            ['name'=>'Jamur Kaleng', 'unit'=>'425', 'default_price'=>'13000', 'satuan'=>'gram'],
            ['name'=>'Wortel', 'unit'=>'1000', 'default_price'=>'14500', 'satuan'=>'gram'],
            ['name'=>'Bombay ( tabur )', 'unit'=>'1000', 'default_price'=>'22500', 'satuan'=>'gram'],
            ['name'=>'Pre ( tabur )', 'unit'=>'1000', 'default_price'=>'18000', 'satuan'=>'gram'],
            ['name'=>'Saus tomat delmonte ( botol 340 ml )', 'unit'=>'340', 'default_price'=>'16000', 'satuan'=>'ml'],
            ['name'=>'Susu indomilk 370 gr', 'unit'=>'370', 'default_price'=>'13500', 'satuan'=>'ml'],
            ['name'=>'Raja rasa 600', 'unit'=>'600', 'default_price'=>'31700', 'satuan'=>'gram'],
            ['name'=>'Kecap 150', 'unit'=>'625', 'default_price'=>'21500', 'satuan'=>'ml'],
            ['name'=>'Maizena', 'unit'=>'1000', 'default_price'=>'16000', 'satuan'=>'gram'],
            ['name'=>'Gula ( tambahan )', 'unit'=>'1000', 'default_price'=>'14500', 'satuan'=>'gram'],
            ['name'=>'Mentega', 'unit'=>'5000', 'default_price'=>'110000', 'satuan'=>'gram'],
            ['name'=>'Roombutter', 'unit'=>'340', 'default_price'=>'92500', 'satuan'=>'gram'],
            ['name'=>'Ayam kampung', 'unit'=>'1000', 'default_price'=>'90000', 'satuan'=>'gram'],
            ['name'=>'Bawang merah', 'unit'=>'1000', 'default_price'=>'38000', 'satuan'=>'gram'],
            ['name'=>'Bawang pre', 'unit'=>'1000', 'default_price'=>'18000', 'satuan'=>'gram'],
            ['name'=>'Bawang bombay', 'unit'=>'1000', 'default_price'=>'22500', 'satuan'=>'gram'],
            ['name'=>'Seledri', 'unit'=>'1000', 'default_price'=>'25000', 'satuan'=>'gram'],
            ['name'=>'Sasa', 'unit'=>'250', 'default_price'=>'12400', 'satuan'=>'gram'],
            ['name'=>'Garam', 'unit'=>'250', 'default_price'=>'1950', 'satuan'=>'gram'],
            ['name'=>'Knor ayam', 'unit'=>'1000', 'default_price'=>'91700', 'satuan'=>'gram'],
            ['name'=>'Gula', 'unit'=>'1000', 'default_price'=>'14500', 'satuan'=>'gram'],
            ['name'=>'Merica', 'unit'=>'1000', 'default_price'=>'92000', 'satuan'=>'gram'],
            ['name'=>'Pala', 'unit'=>'1000', 'default_price'=>'130000', 'satuan'=>'gram'],
            ['name'=>'Air ( 3000 air kaldu )', 'unit'=>'18000', 'default_price'=>'5000', 'satuan'=>'ml'],
            ['name'=>'Daging sapi', 'unit'=>'1000', 'default_price'=>'100000', 'satuan'=>'gram'],
            ['name'=>'Tapioka tani', 'unit'=>'1000', 'default_price'=>'27400', 'satuan'=>'gram'],
            ['name'=>'Bawang putih', 'unit'=>'1000', 'default_price'=>'40000', 'satuan'=>'gram'],
            ['name'=>'Telur', 'unit'=>'1000', 'default_price'=>'23500', 'satuan'=>'gram'],
            ['name'=>'Champ ayam ( isi 15 )', 'unit'=>'375', 'default_price'=>'18000', 'satuan'=>'gram'],
            ['name'=>'Jamur kaleng', 'unit'=>'425', 'default_price'=>'13000', 'satuan'=>'gram'],
            ['name'=>'Kembang tahu', 'unit'=>'150', 'default_price'=>'32000', 'satuan'=>'gram'],
            ['name'=>'Kincam ( bunga sedap malam )', 'unit'=>'1000', 'default_price'=>'85000', 'satuan'=>'gram'],
            ['name'=>'Bombay', 'unit'=>'1000', 'default_price'=>'22500', 'satuan'=>'gram'],
            ['name'=>'Knor', 'unit'=>'1000', 'default_price'=>'91700', 'satuan'=>'gram'],
            ['name'=>'Ayam dada', 'unit'=>'1000', 'default_price'=>'47000', 'satuan'=>'gram'],
            ['name'=>'Ayam sayur', 'unit'=>'1', 'default_price'=>'35000', 'satuan'=>'gram'],
            ['name'=>'Air', 'unit'=>'18000', 'default_price'=>'5000', 'satuan'=>'ml'],
            ['name'=>'Kayu Manis(20 cm)', 'unit'=>'1000', 'default_price'=>'120000', 'satuan'=>'gram'],
            ['name'=>'Kayu Secang', 'unit'=>'50', 'default_price'=>'7000', 'satuan'=>'gram'],
            ['name'=>'Pekak ( 6 biji)', 'unit'=>'1000', 'default_price'=>'230000', 'satuan'=>'gram'],
            ['name'=>'Cengkeh (4 biji)', 'unit'=>'1000', 'default_price'=>'230000', 'satuan'=>'gram'],
            ['name'=>'Daun Pre', 'unit'=>'1000', 'default_price'=>'18000', 'satuan'=>'gram'],
            ['name'=>'Chicken Powder', 'unit'=>'1000', 'default_price'=>'88300', 'satuan'=>'gram'],
            ['name'=>'Merica hitam whole ( 10 biji)', 'unit'=>'1000', 'default_price'=>'120000', 'satuan'=>'gram'],
            ['name'=>'Gula Bebeko', 'unit'=>'1000', 'default_price'=>'42000', 'satuan'=>'gram'],
            ['name'=>'Pewarna red powder', 'unit'=>'500', 'default_price'=>'420000', 'satuan'=>'gram'],
            ['name'=>'Cuka', 'unit'=>'600', 'default_price'=>'16000', 'satuan'=>'ml'],
            ['name'=>'Hoisin saos', 'unit'=>'2250', 'default_price'=>'126635', 'satuan'=>'gram'],
            ['name'=>'Ayam paha tempongan', 'unit'=>'1000', 'default_price'=>'33000', 'satuan'=>'gram'],
            ['name'=>'Jahe ( dihaluskan )', 'unit'=>'1000', 'default_price'=>'25000', 'satuan'=>'gram'],
            ['name'=>'Cabe rawit', 'unit'=>'1000', 'default_price'=>'80000', 'satuan'=>'gram'],
            ['name'=>'Cabe merah', 'unit'=>'1000', 'default_price'=>'67000', 'satuan'=>'gram'],
            ['name'=>'Gula merah', 'unit'=>'1000', 'default_price'=>'17500', 'satuan'=>'gram'],
            ['name'=>'Royco', 'unit'=>'10', 'default_price'=>'475', 'satuan'=>'gram'],
            ['name'=>'Sereh', 'unit'=>'1000', 'default_price'=>'12000', 'satuan'=>'gram'],
            ['name'=>'Daun jeruk', 'unit'=>'1000', 'default_price'=>'20000', 'satuan'=>'gram'],
            ['name'=>'Kemangi', 'unit'=>'1000', 'default_price'=>'25000', 'satuan'=>'gram'],
            ['name'=>'Minyak goreng', 'unit'=>'18000', 'default_price'=>'325000', 'satuan'=>'ml'],
            ['name'=>'Brokoli', 'unit'=>'1000', 'default_price'=>'41000', 'satuan'=>'gram'],
            ['name'=>'Brungkul', 'unit'=>'1000', 'default_price'=>'12000', 'satuan'=>'gram'],
            ['name'=>'Sosis cham ayam', 'unit'=>'375', 'default_price'=>'18000', 'satuan'=>'gram'],
            ['name'=>'Jamur kuping', 'unit'=>'1000', 'default_price'=>'260000', 'satuan'=>'gram'],
            ['name'=>'Kapri', 'unit'=>'1000', 'default_price'=>'75000', 'satuan'=>'gram'],
            ['name'=>'Telur puyuh', 'unit'=>'1', 'default_price'=>'500', 'satuan'=>'gram'],
            ['name'=>'Raja rasa', 'unit'=>'600', 'default_price'=>'31700', 'satuan'=>'gram'],
            ['name'=>'Minyak wijen', 'unit'=>'625', 'default_price'=>'37500', 'satuan'=>'ml'],
            ['name'=>'Saus tiram', 'unit'=>'770', 'default_price'=>'53000', 'satuan'=>'ml'],
            ['name'=>'Kecap asin', 'unit'=>'625', 'default_price'=>'36600', 'satuan'=>'ml'],
            ['name'=>'Air kaldu', 'unit'=>'18000', 'default_price'=>'5000', 'satuan'=>'ml'],
            ['name'=>'Tofu', 'unit'=>'1', 'default_price'=>'9900', 'satuan'=>'gram'],
            ['name'=>'Udang', 'unit'=>'1000', 'default_price'=>'85000', 'satuan'=>'gram'],
            ['name'=>'Baby pakchoy', 'unit'=>'1000', 'default_price'=>'10000', 'satuan'=>'gram'],
            ['name'=>'Jamur payung', 'unit'=>'1000', 'default_price'=>'260000', 'satuan'=>'gram'],
            ['name'=>'Agar - agar sakura', 'unit'=>'10', 'default_price'=>'3300', 'satuan'=>'gram'],
            ['name'=>'Agar - agar bola dunia', 'unit'=>'7', 'default_price'=>'4800', 'satuan'=>'gram'],
            ['name'=>'Gula pasir', 'unit'=>'1000', 'default_price'=>'14500', 'satuan'=>'gram'],
            ['name'=>'Susu Indo milk', 'unit'=>'370', 'default_price'=>'13500', 'satuan'=>'ml'],
            ['name'=>'Degan', 'unit'=>'1', 'default_price'=>'9000', 'satuan'=>'gram'],
            ['name'=>'Leci kaleng', 'unit'=>'1', 'default_price'=>'23750', 'satuan'=>'gram'],
            ['name'=>'Nata de coco slice', 'unit'=>'1000', 'default_price'=>'18500', 'satuan'=>'gram'],
            ['name'=>'Nata de coco dadu', 'unit'=>'1000', 'default_price'=>'21000', 'satuan'=>'gram'],
            ['name'=>'Syirup leci freish', 'unit'=>'460', 'default_price'=>'11000', 'satuan'=>'gram'],
            ['name'=>'Es batu', 'unit'=>'10000', 'default_price'=>'10000', 'satuan'=>'gram'],
            ['name'=>'Gula putih', 'unit'=>'1000', 'default_price'=>'14500', 'satuan'=>'gram'],
            ['name'=>'Alpukat', 'unit'=>'1000', 'default_price'=>'30000', 'satuan'=>'gram'],
            ['name'=>'Tape singkong', 'unit'=>'500', 'default_price'=>'10000', 'satuan'=>'gram'],
            ['name'=>'Ketan hitam', 'unit'=>'1000', 'default_price'=>'25000', 'satuan'=>'gram'],
            ['name'=>'Ketan putih', 'unit'=>'1000', 'default_price'=>'16000', 'satuan'=>'gram'],
            ['name'=>'Ragi', 'unit'=>'28', 'default_price'=>'4500', 'satuan'=>'gram'],
            ['name'=>'Nangka', 'unit'=>'6000', 'default_price'=>'80000', 'satuan'=>'gram'],
            ['name'=>'Mutiara', 'unit'=>'1', 'default_price'=>'1800', 'satuan'=>'gram'],
            ['name'=>'Kolang kaling', 'unit'=>'1000', 'default_price'=>'21000', 'satuan'=>'gram'],
            ['name'=>'Gulaku', 'unit'=>'1000', 'default_price'=>'14500', 'satuan'=>'gram'],
            ['name'=>'Essense Mum', 'unit'=>'40', 'default_price'=>'9000', 'satuan'=>'gram'],
            ['name'=>'Susu Cornation', 'unit'=>'495', 'default_price'=>'13500', 'satuan'=>'ml'],
            ['name'=>'Pete', 'unit'=>'1000', 'default_price'=>'180000', 'satuan'=>'gram'],
            ['name'=>'Terasi', 'unit'=>'1', 'default_price'=>'1500', 'satuan'=>'gram'],
            ['name'=>'Tomat', 'unit'=>'1000', 'default_price'=>'12000', 'satuan'=>'gram'],
            ['name'=>'Laos', 'unit'=>'1000', 'default_price'=>'15000', 'satuan'=>'gram'],
            ['name'=>'Daun salam', 'unit'=>'1000', 'default_price'=>'10000', 'satuan'=>'gram'],
            ['name'=>'Santan ( 4 btr kelapa )', 'unit'=>'1000', 'default_price'=>'12000', 'satuan'=>'ml'],
            ['name'=>'Bawang merag goreng', 'unit'=>'600', 'default_price'=>'88945', 'satuan'=>'gram'],
            ['name'=>'Bawang putih goreng', 'unit'=>'600', 'default_price'=>'75498', 'satuan'=>'gram'],
        ];
        foreach($saveList as $save){
            Ingredients::firstOrCreate(['name'=>$save['name'],'satuan'=>$save['satuan'],'unit'=>$save['unit']],$save);
        }
    }
}
