<?php

namespace Database\Seeders;

use App\Models\CategoryMenusCatering;
use App\Models\MenusCatering;
use Illuminate\Database\Seeder;

class MenuCateringSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $saveList=[
            ['name'=>'SUP SEHAT', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP AYAM JAMUR', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'ASEM - ASEM JAKARTA', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP PANCAWARNA', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP ANEKA SAYUR', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP KIMLO', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP SOSIS JAGUNG MANIS', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP ANEKA SOSIS', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SAYUR ASEM JAWA', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP WONTON', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP AYAM KAMPUNG', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP BOLA - BOLA UDANG', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP MERAH', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP IGA TANPA TULANG', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP ASPARAGUS KEPITING AYAM', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP CREAM (AYAM, JAGUNG, DLL)', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP ASAM PEDAS SZECHUAN', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SU SEAFOOD', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP TOM YAM', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP ROLADE UDANG', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP TAHU SUTERA', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP BUNTUT', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'SUP TIMLO', 'category_menus_catering_id'=>'SUP / SOUP', 'desc'=>''],
            ['name'=>'AYAM BAKAR MADU', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM OVEN MENTEGA', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN GRILL BARBEQUE', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN GRILL SAMBEL MATAH', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN GRILL BLACKPAPER SAUCE', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN GRILL BROWN SAUCE', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN GRILL TERIYAKI SAUCE', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM SAUS LEMON', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM TERIYAKI', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM GORENG KREMES', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM GORENG JAWA', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'ROLADE AYAM', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN KATSU CHILI MAYONAISE', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM GORENG TERASI', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM GORENG LAOS', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM KALASAN', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM RICA - RICA', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM KECAP MENTEGA', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM SAUS INGGRIS', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM CANTON', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN PAULIETA WITH MUSHROOM', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'SATE AYAM LILA CATERING', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM GORENG SAUS THAILAND', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM SAUS ASAM MANIS', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM GORENG PANDAN', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN DRUM STICK', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN CORDON BLEU', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM SAUS LADA HITAM', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM MASAK TRADISIONAL', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM KACANG POLONG', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'CHICKEN PAPRIKA', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'AYAM KUNGPAO', 'category_menus_catering_id'=>'CHICKEN / AYAM', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS ASAM MANIS', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS LEMON', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS TELUR ASIN', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS RICA - RICA', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS THAILAND', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS PADANG', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS KUNGPAO', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS LADA HITAM', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name'=>'GURAMI / KAKAP / DORRY SAUS MANGGA', 'category_menus_catering_id'=>'FISH / IKAN', 'desc'=>''],
            ['name' => 'ANEKA GORENGAN', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'BOLA - BOLA UDANG RAMBUTAN', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'LUMPIA SHANGHAI', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'FRIED WONTON', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'MIX BALL SEAFOOD', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'ANEKA SEAFOOD GORENG', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'SEAFOOD GORENG SAUS KUNGPAO', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'SEAFOOD SAUS RICA - RICA', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG SELIMUT RAMBUTAN', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'SEAFOOD SAUS PAPRIKA', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'CUMI SOTONG ASAM MANIS', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG BAKAR BARBEQUE', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG TELUR ASIN', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG SHANGHAI', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG TEMPURA', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'KEPITING SOKA ANEKA SAUS', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'CUMI CABE IJO', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'CUMI MASAK HITAM', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'MIX SEAFOOD ANEKA SAUS', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG SAUS KUNGPAO', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'UDANG TEPUNG ROTI', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'SAMBEL GORENG UDANG', 'category_menus_catering_id' => 'SEAFOOD', 'desc' => ''],
            ['name' => 'BOLA DAGING SAUS TIRAM PAPRIKA', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'ROLADE DAGING / GALANTINE', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'RENDANG MERAH / COKLAT', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'EMPAL GEPUK', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'PARU PEDAS', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'PARU LOMBOK IJO', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SEMUR DAGING & KENTANG', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SEMUR LIDAH', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF ROLL', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'IGA MASAK PEDAS & KENTANG', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'OSENG KIKIL LOMBOK IJO', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'DAGING LADA HITAM', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'KRENGSENGAN DAGING', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'OSENG LIDAH MASAK JAGUNG', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'OSENG LIDAH LOMBOK IJO', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF STEAK', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF KUNGPAO', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'IGA SAUS BARBEQUE', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF SINGAPORE', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF HONGKONG', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF BARBEQUE', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF BULGOGI', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF SAUS TIRAM', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'BEEF TERIYAKI', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SAMBEL GORENG PRINTIL SAPI', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SAMBEL GORENG CECEK EMBUS', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SAMBEL GORENG PRINTIL + TELUR PUYUH', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SAMBEL GORENG CAMPUR', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'SAMBEL GORENG KIKIL', 'category_menus_catering_id' => 'DAGING / BEEF', 'desc' => ''],
            ['name' => 'CHA BROKOLI AYAM', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA ANEKA SOSIS', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BABY KOL AYAM', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CAP JAY', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'BON CHA KEE', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA KAILAN AYAM', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'TUMIS POKCHOY AYAM', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BABY KOL BOLA DAGING', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA KAILAN BOLA DAGING', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BROKOLI DAGING', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA ANEKA BAKSO', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA AYAM TOFU', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BABY BUNCIS', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BABY KOL DAGING', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA KAILAN UDANG', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA KAILAN DAGING', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'TUMIS POKCHOY DAGING', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BROKOLI WITH GARLIC', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA BROKOLI JAMUR SITAKE', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA JAGUNG MUDA DAGING SITAKE', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA LIDAH BAKSO SAPI', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'GREEN VEGETABLE WITH MUSHROOM', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'CHA SAYUR DAGING ASAP PEDAS', 'category_menus_catering_id' => 'SAYURAN / VEGETABLE', 'desc' => ''],
            ['name' => 'NASI GORENG ANEKA SOSIS', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG MAWUT', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG HONGKONG', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG CURRY', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG HIJAU', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG JAWA', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG IKAN ASIN', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG THAILAND', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG HAINAN', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG SEAFOOD', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'NASI GORENG SINGAPORE', 'category_menus_catering_id' => 'NASI GORENG / FRIED RICE', 'desc' => ''],
            ['name' => 'BAKMI GORENG JAWA', 'category_menus_catering_id' => 'MIE / NOODLES', 'desc' => ''],
            ['name' => 'SUUN CHA JAMUR', 'category_menus_catering_id' => 'MIE / NOODLES', 'desc' => ''],
            ['name' => 'BIHUN SAYUR', 'category_menus_catering_id' => 'MIE / NOODLES', 'desc' => ''],
            ['name' => 'CHA SUUN TELUR', 'category_menus_catering_id' => 'MIE / NOODLES', 'desc' => ''],
            ['name' => 'KWETIAU GORENG', 'category_menus_catering_id' => 'MIE / NOODLES', 'desc' => ''],
            ['name' => 'MONGOLIAN', 'category_menus_catering_id' => 'MIE / NOODLES', 'desc' => ''],
            ['name' => 'ES DEGAN LECI', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES DOGER', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES KOPYOR', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES MANADO', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'RUJAK GOBET', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES DEGAN KUWUT', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES DEGAN JERUK', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES OYEN', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES TELER PINK', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES DAWET AYU', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES DEGAN GULA MERAH', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'BLUE OCEAN ICE', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES SARANG BURUNG', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'FRESH COCKTAIL ICE', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES TELER PUTIH', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES CAMPUR MALAYSIA', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'ES CAMPUR SINGAPORE', 'category_menus_catering_id' => 'DESSERT', 'desc' => ''],
            ['name' => 'PUDING ALMOND', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING BLUBERRY', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'FRUIT PUDING', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING CAPPUCINO', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING CARAMEL', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING DURIAN', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING MOCCA', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING TAPE KETAN', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING LUMUT', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'PUDING KLEPON', 'category_menus_catering_id' => 'ANEKA PUDING', 'desc' => ''],
            ['name' => 'INFUSED WATER', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'SOFT DRINK', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'ANEKA JUICE', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'MINUMAN TRADISIONAL', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'ANEKA PUNCH', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'MOJITO', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'SMOOTHIES', 'category_menus_catering_id' => 'BEVERAGE', 'desc' => ''],
            ['name' => 'SOES / ÉCLAIR', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'ANEKA PASTRY', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'ROLL MINI CAKE', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'KUE TEDOKAN', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'BROWNIES', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'CROISSANT', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'CUP CAKE', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'MINI DONUT', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'PIE BUAH', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'BRUCHETTA', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'MINI PIZZA', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'ROTI JOHN', 'category_menus_catering_id' => 'KUE MINI', 'desc' => ''],
            ['name' => 'ANEKA SOSIS GRILL', 'category_menus_catering_id' => 'HAPPY MENU', 'desc' => ''],
            ['name' => 'ROTI JOHN', 'category_menus_catering_id' => 'HAPPY MENU', 'desc' => ''],
            ['name' => 'BRUCHETTA', 'category_menus_catering_id' => 'HAPPY MENU', 'desc' => ''],
            ['name' => 'MINI BURGER', 'category_menus_catering_id' => 'HAPPY MENU', 'desc' => ''],
            ['name' => 'VEGETABLE TEMPURA', 'category_menus_catering_id' => 'HAPPY MENU', 'desc' => ''],
            ['name' => 'FUYUNGHAI', 'category_menus_catering_id' => 'MENU HEMAT', 'desc' => ''],
            ['name' => 'ONION RINGS', 'category_menus_catering_id' => 'MENU HEMAT', 'desc' => ''],
            ['name' => 'OMELET', 'category_menus_catering_id' => 'MENU HEMAT', 'desc' => ''],
            ['name' => 'JAMUR CRISPY', 'category_menus_catering_id' => 'MENU HEMAT', 'desc' => ''],
            ['name' => 'TAHU LADA GARAM', 'category_menus_catering_id' => 'MENU HEMAT', 'desc' => ''],
            ['name' => 'SAMBEL GORENG TELUR PUYUH', 'category_menus_catering_id' => 'SAMBEL GORENG', 'desc' => ''],
            ['name' => 'SAMBEL GORENG PRINTIL AYAM', 'category_menus_catering_id' => 'SAMBEL GORENG', 'desc' => ''],
            ['name' => 'SAMBEL GORENG ATI AMPELA & KENTANG', 'category_menus_catering_id' => 'SAMBEL GORENG', 'desc' => ''],
            ['name' => 'SAMBEL GORENG KENTANG', 'category_menus_catering_id' => 'SAMBEL GORENG', 'desc' => ''],
            ['name' => 'LASAGNA', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'FETTUCINI', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'SPAGHETTI', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'MACARONI SCHOOTEL', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'PASTEL TUTUP', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'CANNELLONI', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'PENNE WITH TUNA', 'category_menus_catering_id' => 'ANEKA PASTA', 'desc' => ''],
            ['name' => 'FESTIVAL PUDING', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'SMOOTHIES STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'PUFF STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'FESTIVAL JAJANAN JADUL', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'FRUIT FALL', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'NOODLE STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'PARADE JUS', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'D\'CREPES', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'COKLAT FOUNTAIN', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'GELATO', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'MINI CAFÉ', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'ANEKA CAKE TABLE', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'PODJOK DOELOE', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'ZUPPA SOUP', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'PARADE BUAH POTONG', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'GALANTINE STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'KEBAB STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'COFFEE CORNER', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'STEAK STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'JAPANESE STATION', 'category_menus_catering_id' => 'STATION', 'desc' => ''],
            ['name' => 'NASI PECEL', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'NASI UDUK', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'NASI PADANG', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'NASI GUDEG JOGJA', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'NASI KRAWU GRESIK', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'LONTONG CAP GOMEK', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'NASI PESISIR', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'NASI IGA BAKAR', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'LONTONG SATE AYAM', 'category_menus_catering_id' => 'MINI BUFFET', 'desc' => ''],
            ['name' => 'CHICKEN KATSU', 'category_menus_catering_id' => 'JAPANESE FOOD', 'desc' => ''],
            ['name' => 'SUSHI', 'category_menus_catering_id' => 'JAPANESE FOOD', 'desc' => ''],
            ['name' => 'SUKIYAKI', 'category_menus_catering_id' => 'JAPANESE FOOD', 'desc' => ''],
            ['name' => 'DIMSUM', 'category_menus_catering_id' => 'MANDARIAN FOOD', 'desc' => ''],
            ['name' => 'SINGAPORE STEAMBOAT', 'category_menus_catering_id' => 'MANDARIAN FOOD', 'desc' => ''],
            ['name' => 'BEBEK PEKING', 'category_menus_catering_id' => 'MANDARIAN FOOD', 'desc' => ''],
            ['name' => 'ANEKA GORENGAN', 'category_menus_catering_id' => 'MANDARIAN FOOD', 'desc' => ''],
            ['name' => 'AYAM CANTON + NASI HAINAN', 'category_menus_catering_id' => 'MANDARIAN FOOD', 'desc' => ''],
            ['name' => 'KAMBING GULING', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'KAMBING OVEN', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'NASI KEBULI', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'NASI BRIYANI', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'GULAI KAMBING ROTI JALA', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'KEBAB', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'MARTABAK', 'category_menus_catering_id' => 'ARABIAN FOOD', 'desc' => ''],
            ['name' => 'BAKSO CAMPUR', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'LONTONG KIKIL', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'TAHU CAMPUR', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SOTO DAGING', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'LONTONG SATE GULE KAMBING', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'MIE AYAM', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SOUP IGA & NASI', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'RACIKAN SELAT SOLO', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'COTO MAKASSAR', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'TENGKLENG SOLO', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'EMPAL GENTONG', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'TEKWAN', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'GARANG ASEM + NASI', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SOTO AYAM + NASI', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SOTO MIE', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'BAKMOY', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'BAKWAN MALANG', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SOUP TIMLO SOLO', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SOUP TEKWAN', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'BATAGOR', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'PEMPEK PALEMBANG', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'SIOMAY', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'DAWET AYU', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'BUBUR KOMBINASI', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
            ['name' => 'ES PUTER ANEKA RASA', 'category_menus_catering_id' => 'INDONESIAN FOOD', 'desc' => ''],
        ];
        $listCategory=[];
        $list=['SUP MERAH','SUP SEHAT','AYAM CANTON','AYAM RICA - RICA','CHA BROKOLI AYAM','CHA AYAM TOFU','ES DEGAN LECI','ES DOGER','SAMBEL GORENG UDANG','SAMBEL GORENG PRINTIL SAPI'];
        foreach($saveList as $save){
            if(!in_array($save['category_menus_catering_id'],array_keys($listCategory))){
                $subId=CategoryMenusCatering::where(['name'=>$save['category_menus_catering_id']])->select(['id'])->first();
                if($subId){
                    $listCategory[$save['category_menus_catering_id']]=$subId->id;
                }
            }
            $save['is_active']=in_array($save['name'],$list)?1:0;
            $save['porsi_standard']=rand(1,10)*100;
            $save['selling_price']=$save['porsi_standard']*(rand(1,10)*rand(1,10)*100);
            $save['category_menus_catering_id']=$listCategory[$save['category_menus_catering_id']];
            MenusCatering::firstOrCreate(['name'=>$save['name'],'category_menus_catering_id'=>$save['category_menus_catering_id']],$save);
        }
    }
}
