[supervisord]
logfile=/dev/null            ; main log file; default $CWD/supervisord.log
logfile_maxbytes=0           ; max main logfile bytes b4 rotation; default 50MB
logfile_backups=10           ; # of main logfile backups; 0 means none, default 10
loglevel=info                ; log level; default info; others: debug,warn,trace
pidfile=/run/supervisord.pid ; supervisord pidfile; default supervisord.pid
nodaemon=true               ; start in foreground if true; default false
minfds=1024                  ; min. avail startup file descriptors; default 1024
minprocs=200                 ; min. avail process descriptors;default 200

[program:apache2]
command=apachectl -D "FOREGROUND" -k start
redirect_stderr=true

[program:crond]
command=cron -f
redirect_stderr=true

[program:import_temp]
directory=/var/www/html
process_name=%(process_num)02d
command=php artisan queue:listen --queue=import_temp --timeout=0 --sleep=5
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile= /var/log/supervisor/worker-import_temp.log
stopwaitsecs=3600
